version: "3.4"

services:
  data:
    image: mongo
    restart: always
  
  bot:
    build: ./bot
    restart: always
    environment:
      - DISCORD_TOKEN
      - DISCORD_OWNER
      - DISCORD_CTFS_CHANNEL
      - DATA_CONNECTION_URI
  