version: "3.4"

services:
  data:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db
  
  bot:
    build: ./bot
    restart: always
    depends_on:
      - data
    environment:
      - DISCORD_TOKEN
      - DISCORD_OWNER
      - DISCORD_CTFS_CHANNEL
      - DISCORD_UPCOMING_CHANNEL
      - DATA_CONNECTION_URI
  